version: "2"
services:
  example-component:
    image: andrewshawcare/component-workshop
    environment:
      - COMPONENT_PATH=./example-component
    ports:
      - '80:80'
      - '35729:35729'
    volumes:
      - ./:/usr/src/app/example-component
